name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '16'  # You can also specify '20' if your project is compatible

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start &
        env:
          CI: true

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          CI: true
